version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "yKicchan"
    open-pull-requests-limit: 20
